Public Class form_LogModificacoes
    Private Sub form_LogModificacoes_Load(sender As Object, e As EventArgs) Handles MyBase.Load

        dgv_HistMod.Rows.Add("19/04/2021", "Adicionado Automação do Painel Operacional BKB")
        dgv_HistMod.Rows.Add("27/04/2021", "Fim dos testes da Automação do Painel Operacional BKB")
        dgv_HistMod.Rows.Add("04/05/2021", "Início Automação do Painel Operacional PLK")
        dgv_HistMod.Rows.Add("05/05/2021", "Adicionado Automação do Painel Operacional PLK")
        dgv_HistMod.Rows.Add("06/05/2021", "Adicionado Histórico de Modificações")
        dgv_HistMod.Rows.Add("10/05/2021", "Início Automação do Painel Operacional FZ")
        dgv_HistMod.Rows.Add("11/05/2021", "Fim dos testes da Automação do Painel Operacional PLK")
        dgv_HistMod.Rows.Add("12/05/2021", "Adicionado Automação do Painel Operacional FZ")
        dgv_HistMod.Rows.Add("13/05/2021", "Fim dos testes da Automação do Painel Operacional FZ")
        dgv_HistMod.Rows.Add("13/05/2021", "Início Automação do Painel de Labor PLK")
        dgv_HistMod.Rows.Add("13/05/2021", "Adicionado Automação do Painel Labor PLK")
        dgv_HistMod.Rows.Add("13/05/2021", "Fim dos testes da Automação do Painel Labor PLK")
        dgv_HistMod.Rows.Add("17/05/2021", "Início Automação do Painel de CMV PLK")
        dgv_HistMod.Rows.Add("18/05/2021", "Adicionado Automação do Painel CMV PLK")
        dgv_HistMod.Rows.Add("19/05/2021", "Fim dos testes da Automação do Painel CMV PLK")
        dgv_HistMod.Rows.Add("19/05/2021", "Correção da Propagação de Fórmulas do Painel de Labor aba Estatística das Marcações.")
        dgv_HistMod.Rows.Add("20/05/2021", "Estilização de Formulários - Menu Principal.")
        dgv_HistMod.Rows.Add("20/05/2021", "Estilização de Formulários - Painel CMV PLK.")
        dgv_HistMod.Rows.Add("20/05/2021", "Estilização de Formulários - Painel Operacional FZ.")
        dgv_HistMod.Rows.Add("20/05/2021", "Estilização de Formulários - Loading.")
        dgv_HistMod.Rows.Add("24/05/2021", "Estilização de Formulários - Painel Operacional PLK.")
        dgv_HistMod.Rows.Add("24/05/2021", "Estilização de Formulários - Painel Labor PLK.")
        dgv_HistMod.Rows.Add("25/05/2021", "Estilização de Formulários - Painel Operacional BKB.")
        dgv_HistMod.Rows.Add("26/05/2021", "Estilização de MsgBox.")
        dgv_HistMod.Rows.Add("27/05/2021", "Correção fechar do Loading.")
        dgv_HistMod.Rows.Add("31/05/2021", "Correção Bug do Loading no Painel CMV.")
        dgv_HistMod.Rows.Add("02/06/2021", "Correção das colunas do Disp PDV e Disp PDV Consolidado - Painel Disponibilidade BKB.")
        dgv_HistMod.Rows.Add("04/06/2021", "Correção colunas Relatório Restaurante - Painel CMV PLK.")
        dgv_HistMod.Rows.Add("09/06/2021", "Propagar fórmulas Painel Disponibilidade - abas 'Colar em Disp PDV' e 'Colar em Consolidado'")
        dgv_HistMod.Rows.Add("09/06/2021", "Propagar fórmulas Painel Ops FZ - aba 'Colar em Disp PDV'")
        dgv_HistMod.Rows.Add("09/06/2021", "Propagar fórmulas Painel de Horas - abas 'Colar em Disp PDV' e 'Colar em Consolidado'")
        dgv_HistMod.Rows.Add("09/06/2021", "Propagar Formatação Condicional Painel Ops BKB e FZ - abas 'Colar em Disp PDV' e 'Colar em Consolidado'")
        dgv_HistMod.Rows.Add("10/06/2021", "Correção colunas e linhas Ranking Diário. - BKB, PLK e FZ")
        dgv_HistMod.Rows.Add("10/06/2021", "Desfazendo correção da coluna a mais na aba Setor do Ranking Diário. - BKB, PLK e FZ")
        dgv_HistMod.Rows.Add("12/06/2021", "Refazendo correção da coluna a mais na aba Setor do Ranking Diário. - BKB, PLK e FZ")
        dgv_HistMod.Rows.Add("17/06/2021", "Inserido AUVs. - PLK")
        dgv_HistMod.Rows.Add("24/06/2021", "Correção Ranking Diário - BKB, PLK e FZ")
        dgv_HistMod.Rows.Add("24/06/2021", "Correção Progressbar - Operacional PLK")
        dgv_HistMod.Rows.Add("05/07/2021", "Atualização Novo Painel CMV")
        dgv_HistMod.Rows.Add("12/07/2021", "Colar Valor nas fórmulas do Base Dinâmica Vendas - FZ e PLK")
        dgv_HistMod.Rows.Add("14/07/2021", "Correção Colar Valor nas fórmulas do Base Dinâmica Vendas - PLK")
        dgv_HistMod.Rows.Add("14/07/2021", "Correção Propagar fórmulas do RELATÓRIO DE VENDA - CMV PLK")
        dgv_HistMod.Rows.Add("30/07/2021", "Atualização Painel de Horas - BKB")
        dgv_HistMod.Rows.Add("08/10/2021", "Atualização 6.1 Delivery Tempo e Notas - BKB, PLK e FZ")
        dgv_HistMod.Rows.Add("16/11/2021", "Inserção Clube BK - BKB")
        dgv_HistMod.Rows.Add("27/01/2022", "Range informações de Restaurantes Ranking Diário - BKB, PLK e FZ")
        dgv_HistMod.Rows.Add("27/01/2022", "Range Comentários Ranking Diário - BKB, PLK e FZ")
        dgv_HistMod.Rows.Add("03/02/2022", "Inserção do Quantidade Sanduíche - BKB")
        dgv_HistMod.Rows.Add("03/03/2022", "Correção arrastar fórmulas aba AUVs - FZ")

    End Sub

End Class